export const SET_LOADING = "SET_LOADING"
export const SET_DETAIL = "SET_DETAIL"
export const SET_TOKEN = "SET_TOKEN"
export const SET_FILTER = "SET_FILTER"
export const SET_RECRUITMENT_LIST = "SET_RECRUITMENT_LIST"
export const SET_ERROR = "SET_ERROR"
